name: deeplinks
description: shelf static handler example
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: any
  path: ^1.8.3
  meta: ^1.9.1

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
